# Generated by Django 5.2.16 on 2026-07-11 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='College Name')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year of Study')),
                ('career_goal', models.TextField(blank=True, null=True, verbose_name='Career Goal')),
                ('github', models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub Profile')),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Profile')),
                ('portfolio', models.URLField(blank=True, max_length=255, null=True, verbose_name='Portfolio URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('skill_level', models.CharField(max_length=50, verbose_name='Skill Level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['student', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/', verbose_name='Resume File')),
                ('resume_text', models.TextField(blank=True, null=True, verbose_name='Resume Text Content')),
                ('resume_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resume Version')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='students.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
