# Generated by Django 5.2.16 on 2026-07-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis_status',
            field=models.CharField(default='Uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_job_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
