# Generated by Django 5.2.16 on 2026-07-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_resume_analysis_status_resume_target_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_version',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='target_job_role',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='Job Description'),
        ),
    ]
