# Generated by Django 5.2.16 on 2026-07-15 03:18

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_resume_resume_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gemini_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
