# Generated by Django 5.2.16 on 2026-07-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(verbose_name='Overall Score')),
                ('technical_score', models.IntegerField(verbose_name='Technical Score')),
                ('resume_quality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resume Quality')),
                ('ats_score', models.IntegerField(verbose_name='ATS Score')),
                ('resume_summary', models.TextField(blank=True, null=True, verbose_name='Resume Summary')),
                ('strengths', models.TextField(blank=True, null=True, verbose_name='Strengths')),
                ('weaknesses', models.TextField(blank=True, null=True, verbose_name='Weaknesses')),
                ('missing_skills', models.TextField(blank=True, null=True, verbose_name='Missing Skills')),
                ('recommended_skills', models.TextField(blank=True, null=True, verbose_name='Recommended Skills')),
                ('learning_priority', models.TextField(blank=True, null=True, verbose_name='Learning Priority')),
                ('recommended_projects', models.TextField(blank=True, null=True, verbose_name='Recommended Projects')),
                ('career_domain', models.TextField(blank=True, null=True, verbose_name='Career Domain')),
                ('job_roles', models.TextField(blank=True, null=True, verbose_name='Job Roles')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, verbose_name='Analysis Date')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_analyses', to='students.resume', verbose_name='Resume')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_analyses', to='students.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
