# Generated by Django 5.2.16 on 2026-07-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('students', '0003_remove_resume_resume_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='career_domain',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='recommended_projects',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='recommended_skills',
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='improvement_tips',
            field=models.TextField(blank=True, null=True, verbose_name='Improvement Tips'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='interview_readiness_score',
            field=models.IntegerField(default=0, verbose_name='Interview Readiness Score'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='students.resume', verbose_name='Resume'),
        ),
    ]
