# Generated by Django 5.2.16 on 2026-07-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_remove_aianalysis_career_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='student',
        ),
    ]
