# Generated by Django 5.2.16 on 2026-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_aianalysis_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='overall_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Overall Feedback'),
        ),
    ]
