# Generated by Django 5.2.16 on 2026-07-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_aianalysis_overall_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='job_match_score',
            field=models.IntegerField(default=0, verbose_name='Job Match Score'),
        ),
    ]
