# Generated by Django 5.2.16 on 2026-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_aianalysis_job_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='found_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Found Skills'),
        ),
    ]
