# Generated by Django 5.2.16 on 2026-07-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_feedbacks', to='students.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Workshop Feedback',
                'verbose_name_plural': 'Workshop Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
